-- find upstream source tables and queries used

WITH access_history as (
SELECT
  QUERY_ID
  , LISTAGG(DISTINCT PARSE_JSON(FJ.VALUE):objectName::STRING, ', ') as SOURCE_TABLES
  , TRIM(OBJECTS_MODIFIED[0].objectName, '"') AS TARGET_TABLE
  FROM SNOWFLAKE.ACOCUNT_USAGE.ACCESS_HISTORY
  , TABLE(FLATTEN(DIRECT_OBJECTS_ACCESSED)) FJ
  WHERE 
    OBJECTS_MODIFIED[0].objectName = $table_name
  -- OBJECTS_MODIFIED[0].objectName ilike '%'||$table_name||'%'
  AND QUERY_START_TIME BETWEEN $start_date AND $end_date
  GROUP BY ALL
)
-- select * from access_history;

SELECT
  AH.QUERY_ID
, QH.USER_NAME
, QH.ROLE_NAME
, QH.START_TIME
, QH.END_TIME
, QH.EXECUTION_TIME
, QH.EXECUTION_STATUS
, QH.ROWS_PRODUCED
, QH.DATABASE_NAME
, QH.SCHEMA_NAME
, QH.WAREHOUSE_SIZE
, QH.QUERY_TYPE
, AH.SOURCE_TABLES
, AH.TARGET_TABLE
, QH.QUERY_TEXT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY  QH
JOIN access_history                         AH ON QH.QUERY_ID = AH.QUERY_ID
WHERE QH.START_TIME BETWEEN $start_date AND $end_date
ORDER BY QH.START_TIME
;

-- find downstream target tables and queries used

WITH access_history as (
SELECT
  QUERY_ID
  , LISTAGG(DISTINCT PARSE_JSON(FJ.VALUE):objectName::STRING, ', ') as TARGET_TABLES
  , TRIM(DIRECT_OBJECTS_ACCESSED[0].objectName, '"') AS SOURCE_TABLE
  FROM SNOWFLAKE.ACOCUNT_USAGE.ACCESS_HISTORY
  , TABLE(FLATTEN(OBJECTS_MODIFIED)) FJ
  WHERE 
    DIRECT_OBJECTS_ACCESSED[0].objectName = $table_name
  -- DIRECT_OBJECTS_ACCESSED[0].objectName ilike '%'||$table_name||'%'
  AND QUERY_START_TIME BETWEEN $start_date AND $end_date
  GROUP BY ALL
)
-- select * from access_history;

SELECT
  AH.QUERY_ID
, QH.USER_NAME
, QH.ROLE_NAME
, QH.START_TIME
, QH.END_TIME
, QH.EXECUTION_TIME
, QH.EXECUTION_STATUS
, QH.ROWS_PRODUCED
, QH.DATABASE_NAME
, QH.SCHEMA_NAME
, QH.WAREHOUSE_SIZE
, QH.QUERY_TYPE
, AH.SOURCE_TABLE
, AH.TARGET_TABLES
, QH.QUERY_TEXT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY  QH
JOIN access_history                         AH ON QH.QUERY_ID = AH.QUERY_ID
WHERE QH.START_TIME BETWEEN $start_date AND $end_date
ORDER BY QH.START_TIME
;
