SELECT
  CURRENT_TIMESTAMP
, START_TIME
, END_TIME
-- , TO_VARCHAR(START_TIME, '%Y-%m-%d HH:MI:SS') AS START_TIME
-- , TO_VARCHAR(END_TIME, '%Y-%m-%d HH:MI:SS') AS END_TIME
, EXECUTION_STATUS, ERROR_CODE, ERROR_MESSAGE, USER_NAME
, ROWS_PRODUCED, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED
, QUERY_TYPE, QUERY_TEXT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= CURRENT_DATE()
AND USER_NAME = ...
AND QUERY_TYPE NOT IN ('SELECT')
ORDER BY START_TIME
;
